-- Supabase SQL Schema for Constitutional Awareness Survey
-- Run this in your Supabase SQL Editor

-- 1. Create responses table
CREATE TABLE IF NOT EXISTS responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  age TEXT,
  gender TEXT,
  department TEXT,
  q1 TEXT, q2 TEXT, q3 TEXT,
  q4 TEXT, q5 TEXT, q6 TEXT,
  q7 TEXT, q8 TEXT,
  q9 TEXT, q10 TEXT, q11 TEXT,
  q12 TEXT,
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create admins table
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- 3. Insert your admin credentials
INSERT INTO admins (username, password) VALUES 
  ('Mma2007', 'Malik_4370che18'),
  ('admin', 'admin123'); -- Keep old one as backup

-- 4. Enable Row Level Security
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- 5. Policies for responses table

-- Allow anyone to insert (public survey submission)
CREATE POLICY "Allow public insert" ON responses
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- Allow anyone to read (for dashboard)
CREATE POLICY "Allow public read" ON responses
  FOR SELECT TO anon, authenticated
  USING (true);

-- 6. Policy for admins table (allow read for login check)
CREATE POLICY "Allow admin read" ON admins
  FOR SELECT TO authenticated
  USING (true);